### ISSUE TITLE
site.url should not be hard-coded to http://

### ISSUE THREAD

**Issue by lwchkg** [jekyll/github-metadata#116]
This breaks https sites. Instead of `http://lwchkg.github.io`, set it to `//lwchkg.github.io` please.

**Comment by pathawks** [comment]
Protocol relative URLs are [an antipattern](https://www.paulirish.com/2010/the-protocol-relative-url/). Is there some way for the plugin to detect if a site uses HTTPS and always use that when available?

**Comment by lwchkg** [comment]
@pathawks With reference to what you say, site.url should be hardcoded to https:// instead of http:// here. There is no need to detect whether the site use HTTPS anyway, because this repo is github specific, which automatically calculates site.url for github pages.

**Comment by parkr** [comment]
I believe we get this information from the server one way or another (Pages.ssl? maybe?), so we don’t want to hard-code anything here. If you’re getting this locally, it’s because the API won’t tell unauthenticated (anon) users anything about Pages by default.

**Comment by lwchkg** [comment]
@parkr I did get nothing for site.url locally with this gem, which is good. Where I get the bad results is the actual GitHub Pages, and that's why I come here for the bug report.

If we didn't hard-code anything in this repo, then yes it means something is wrong in the GitHub servers. (I forgot about the cases about custom domains in a previous comment. But the GitHub employee handling that show know the best anyway. :-) )

**Comment by benbalter** [comment]
Agree with the above, that nothing should be hard coded. Locally, when in development mode, it should default to `http://localhost'. In production, it should use the value passed by the GitHub API which takes into account if the pages has HTTPS enabled and enforced (e.g., a `*.github.io` domain that a user has opted in to use HTTPs). See https://github.com/jekyll/github-metadata/blob/0a5fa43e9c477488a44f6006e95fc91d1e6f4cef/lib/jekyll-github-metadata/repository.rb#L167-L169.

**Comment by lwchkg** [comment]
> if HTTPS enabled and enforced
@benbalter Oh thanks! I didn't recognize the presence of such an option exists (missed the blog posts). I'll enable the option now, and things will be fixed for my site.

Anyway, back to discussion. So the condition for the breakages are:
1. The site does not enforce HTTPS,
2. HTTPS is enabled, and
3. The HTTPS site is used.
(i.e. Legacy users of HTTPS site.)

And now we're certain that the problem lies on the GitHub API, which is outside this repo.

Are any of you GitHub employees, or have connections the GitHub people managing the API? If yes please help me by passing the issue to the right people. (If nobody replies within 48 hours, I assume none of you have connections, and I'll call GitHub support.)

P.S. this issue can be closed if the message is passed to the right people.

**Comment by benbalter** [comment]
@lwchkg If a site has HTTPS enabled and a user manually types `https://` to get to the HTTPS variant, but the owner does not enforce HTTPS, the user may see mixed content warnings. The workaround, as described above, is to manually specify `site.url` in your site's config, which this plugin will respect. GitHub can't automatically set the flag without the user opting in, as it could cause the same mixed content issues. We'd rather give the user the opportunity to make the change and test it out then potentially break a site in a way users may not understand immediately how to fix.

**Comment by mattn** [comment]
GitHub enable HTTPS on GitHub Pages.

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

So `site.url` always be wrong. Most of GitHub users will add workaround `{{ site.url | replace: 'http://', '//'}}`. How about to add new attribute like `site.url_noscheme` or something?

**Comment by parkr** [comment]
This library makes an API request to GitHub to get the URL. If there is no token, then it will always be HTTP. For GitHub Pages requests, the request is authenticated so `site.github.url` should contain `https://` **if you click "Enforce HTTPS" in your repository settings.**
