### ISSUE TITLE
Github metadata out of date

### ISSUE THREAD

**Issue by gkiar** [jekyll/github-metadata#122]
I'm using Jekyll/github-metadata to populate projects on my personal website hosted on Github Pages,
 [gkiar.github.io](https://gkiar.github.io/projects), and notice that the metadata is almost permanently out-of-date.

Is there a workaround for this?

**Comment by benbalter** [comment]
We can't speak to the specifics of your particular site. If you [contact GitHub support](https://github.com/contact) (or [post to the GitHub Community forum](https://github.community/)) they should be able to help you get things straightened out. 😸
