### ISSUE TITLE
Confusing message

### ISSUE THREAD

**Issue by jayvdb** [jekyll/github-metadata#123]
Running this gem on a GitLab repo results in a [strange error in the job log](https://gitlab.com/ciptamedia/ciptamedia-dev.gitlab.io/-/jobs/54868918)

```
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Error processing value 'url':
  Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/base.html
```

For starters, `url` doesnt appear in https://gitlab.com/ciptamedia/ciptamedia-dev.gitlab.io/blob/8c6277532f/_layouts/base.html

I believe this is happening because this gem is trying to set `site.url` as it isnt set in the `_config.yml`.  I also deploy to Netlify, and using https://github.com/jayvdb/jekyll-netlify to set the site.url on that platform, but nothing sets it on GitLab.

**Comment by benbalter** [comment]
@jayvdb This plugin is intended to be used with GitHub, not GitLab.

**Comment by jayvdb** [comment]
That isnt really relevant.  I'm not trying to get it to do GitLab stuff.

`PAGES_REPO_NWO` exists to support being run on non-GitHub projects, or in strange set ups.

Also the plugin is designed to not be intrusive/problematic unless its functionality is used.

In my case I believe it is getting triggered into action by a `site.url`.

The message

> GitHub Metadata: Error processing value 'url':

should probably be

> GitHub Metadata: Error processing 'site' variable 'url':

And it is currently reporting the error in `_layouts/base.html`, when it is likely some deeper nested filename.  This aspect may be beyond the control of this plugin, and thus may need to be raised upstream in jekyll itself (if the problem still exists in the latest jekyll).

**Comment by benbalter** [comment]
@jayvdb Please see [the project readme](https://github.com/jekyll/github-metadata#github-metadata-aka-sitegithub). This project is intended solely to propagate the `site.github` namespace and set default values *for use with GitHub Pages.* It is not intended to be used with any other code or static site hosting service. At this time, we're not able to provide support for use cases beyond those intended. If you believe there is a bug or error in the logic, regardless of use case, we'd be glad to review a pull request to fix it.

**Comment by jayvdb** [comment]
So I need to set up the same scenario on an offline version of a GitHub Pages repo, so you can see the same error that is in the issue but without any mention of other hosting providers.  Only then you will magically be able to see the problem?
