### ISSUE TITLE
Disable network requests

### ISSUE THREAD

**Issue by pathawks** [jekyll/github-metadata#127]
For purposes of benchmarking, it would be nice if the time it takes to request data from the GitHub API did not contribute to the build time. Could an option be added to explicitly set `@internet_connected` to `False`?

https://github.com/jekyll/github-metadata/blob/47855c340dc4ac4e7c7b4db7ab6349c0286ca50e/lib/jekyll-github-metadata/client.rb#L96-L97

Could there be a way to build the site once with networking, retrieve the requested data, and then use only cached data for subsequent builds?

**Comment by benbalter** [comment]
@pathawks glad to review a PR to make that easier to set.... alternatively, VCR or Webmock may help spoof the requests to benchmark the underlying logic without the network request.

**Comment by pathawks** [comment]
@benbalter Could you provide just a bit more detail for how that would work?

For the record, my use case is benchmarking Jekyll sites that depend on this plugin, rather than benchmarking the plugin itself. I want to be able to run something like `jekyll build` and not worry that an inconsistent network connection could be skewing results.

**Comment by benbalter** [comment]
@pathawks are you running it from command line or within a ruby script? If within a ruby script (e.g., bench-marking the actual site execution) prior to starting the timer, you'd require Webmock and disable network connections, stubbing in those you'd expect with JSON files locally. If timing via, e.g., shell, including the Ruby boot time, it wouldn't work, and the option you described above would be the best route.

**Comment by pathawks** [comment]
Plan was from Bash script, but I may need to reconsider.

Closing this until I know if any specific changes need to be made here.
