### ISSUE TITLE
Github repo isn't being detected

### ISSUE THREAD

**Issue by feildmaster** [jekyll/github-metadata#142]
Problem:
```
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Error processing value 'title':
  Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in /_layouts/default.html
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.
```

[As found on configuration:](https://github.com/jekyll/github-metadata/blob/master/docs/configuration.md)
`If you ran git clone from GitHub, this is almost 100% the case & no further action is needed.`

I even went and cloned a repository again, I thought "Perhaps it doesn't like running out of /docs." and configured it to build from root. I do *not* want to use `_config.yml, repository:` and I'd rather not use an environment variable when it's supposed to be grabbed from git.

So why does my repo refuse to be detected?

Also before I forget, I can git remote:
```
git remote -v
origin  https://github.com/feildmaster/UnderScript.git (fetch)
origin  https://github.com/feildmaster/UnderScript.git (push)
```
And another attempt I tried to use:
```
git remote -v
origin  git@github.com:feildmaster/UnderScript.git (fetch)
origin  git@github.com:feildmaster/UnderScript.git (push)
```
(both end with same results)

Also, I'm working on the [pages_test](https://github.com/feildmaster/UnderScript/tree/pages_test) branch

Build Environment:
* Windows 10
* Git 2.19.0.windows.1
* Ruby 2.5.3p105 
* Jekyll 3.7.4
* Gem 2.7.6
* Bundler 1.17.1

**Comment by ashmaroli** [comment]
@feildmaster A fix has been proposed in #136.

**Comment by feildmaster** [comment]
Ahh... Thanks for pointing me there. :)

**Comment by ashmaroli** [comment]
Resolved via https://github.com/jekyll/github-metadata/commit/2f5745b8f91cdf855bd2753be87d3a31b4d53885
