### ISSUE TITLE
Tests fail when origin changed

### ISSUE THREAD

**Issue by mrmanc** [jekyll/github-metadata#148]
When the origin remote of a working copy is changed away from `https://github.com/jekyll/github-metadata.git`, the tests fail. The [failing test](https://github.com/jekyll/github-metadata/blob/master/spec/repository_finder_spec.rb#L28) contains this assertion: `expect(subject.send(:git_remote_url)).to include("jekyll/github-metadata")`. This is a head scratcher when running tests before pushing to a fork in preparation for contribution. I have some changes ready to resolve this.

**Comment by parkr** [comment]
@mrmanc Please PR!

**Comment by parkr** [comment]
I believe #152 completed this!
