### ISSUE TITLE
Public Repos (and other collections) only have first 30 results?

### ISSUE THREAD

**Issue by jarrodparkes** [jekyll/github-metadata#16]
In my markdown files, I am trying to display the names of all public repositories for a particular organization, but it appears that the collection values available in `site.github` only contain 30 entries (likely based on the API's spec that says it [by default] only returns 30).

    {% for repository in site.github.public_repositories %}
            <li>{{ repository.full_name }}</li>
    {% endfor %}

Is there anyway to access more than 30? Or what is the common approach for paginating these results? Is it something I do in Liquid or do I need to write some Ruby, etc.?

I am having a hard time finding information about this because "paginating" already has some relevance as Jekyll feature.

Thanks

**Comment by parkr** [comment]
Can you give #17 a shot when you get a second?

**Comment by jarrodparkes** [comment]
@parkr What am I trying exactly?

**Comment by parkr** [comment]
@jarrodparkes Turning `auto_paginate` off for the client. In your Gemfile:

```ruby
gem "jekyll-github-metadata", github: "jekyll/github-metadata", branch: "parkr-no-auto-paginate"
```

then run `bundle install && bundle exec jekyll serve` and see if it prints more than 30.

**Comment by jarrodparkes** [comment]
@parkr,

I gave it a go, but no change :disappointed: . The Heroku site is hosted at http://udacity-meta.herokuapp.com and the Github repo lives at https://github.com/udacity/meta.
