### ISSUE TITLE
Reopen #130 - Latest Commit Date for File

### ISSUE THREAD

**Issue by BenLeggiero** [jekyll/github-metadata#167]
This is a great feature that I would love to see, but the issue was closed because no human commented on it for 2 months.

Body of the original ticket is below:

---

Per [github/pages-gem#119 (comment)](https://github.com/github/pages-gem/pull/119#issuecomment-283494408)

> Perhaps we could add this to the `site.github` gem (jellyll/github-metadata) as `site.github.commit_dates[<filepath>]` and read them all in bulk from the GraphQL API.

This would be great for "Latest Update" type dates on GitHub Pages, where other plugins are not available.

**Comment by mattr-** [comment]
Duplicate of #130
