### ISSUE TITLE
Faraday::Error::ConnectionFailed has moved since v1.0.0

### ISSUE THREAD

**Issue by satoryu** [jekyll/github-metadata#177]
I tried to update gems used in my github-pages project but the following error appeared when building my project: 

```
          1: from /Users/satoryu/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll-github-metadata-2.12.1/lib/jekyll-github-metadata/client.rb:71:in `save_from_errors'
/Users/satoryu/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll-github-metadata-2.12.1/lib/jekyll-github-metadata/client.rb:80:in `rescue in save_from_errors': uninitialized constant Faraday::Error::ConnectionFailed (NameError)
Did you mean?  Faraday::ConnectionFailed
```

As this error says, 

https://github.com/jekyll/github-metadata/blob/9353743dc9ad6de2f522923d57eb8eb00f87abf6/lib/jekyll-github-metadata/client.rb#L80

the error class `Faraday::Error::ConnectionFailed` has been promoted as one of siblings under `Faraday`. 

https://github.com/lostisland/faraday/blob/master/lib/faraday/error.rb

**Comment by bvhme** [comment]
Thanks everybody for coming together so quickly and fixing this bug!

I hope we can see a release quickly, as that would unblock a whole ton of things for me :)
