### ISSUE TITLE
latest_release does not work and returns empty string

### ISSUE THREAD

**Issue by arxeiss** [jekyll/github-metadata#180]
I see that @Crunch09 created pull request #88 which was merged. But when I'm trying to use that attribute, there is always an empty string.

Trying to do it for repo https://github.com/arxeiss/responsive-pagination and when I use `{{ site.github.latest_release.zipball_url }}` and page https://arxeiss.github.io/responsive-pagination/ it always returns empty string. Am I doing something wrong or it does not work?

**Comment by ashmaroli** [comment]
I think you need to have a *full release* (with a release document) for it to be reflected via the GitHub API.

Compare releases for your repo: https://github.com/arxeiss/responsive-pagination/releases
and for this repo: https://github.com/jekyll/github-metadata/releases

**Comment by arxeiss** [comment]
Yes, my fault, you were correct.

Thank you for quick reply
