### ISSUE TITLE
site.url, do not change HTTP to https after enabling HTTPS on GitHub pages

### ISSUE THREAD

**Issue by BaseMax** [jekyll/github-metadata#194]
Hi there,

After changing the domain or adding a new domain to the repository, even though **HTTPS** is active.
After spend **11 hours** and reviewing the site, we see that the certificate has been applied well and the site is available in the new domain.
But unfortunately, CSS style files are still loaded from **http** protocol.
And that's why interference occurs.
Because the page is in **HTTPS** protocol, but some files (css,js,img) are in HTTP.
`{site.url}`

_layouts/default.html:
```html
    <link rel="shortcut icon" href="{{ site.url }}/favicon.ico">
    <link type="text/css" rel="stylesheet" href="{{ site.url }}/style.css" />
    <link type="text/css" rel="stylesheet" href="{{ site.url }}/style.css">
```

**Solution to fix:**
Just send a new commit to the repository.
This causes the ruby scripts to run and the site to be updated, in which case the value of variable `{site.url}` will change to `HTTPS://...` everywhere.

![DEMO-DEPLOYED](https://user-images.githubusercontent.com/2658040/102716963-76f2a900-42f4-11eb-9345-f10c5e8da84c.png)

But why do we really need to send/push a useless commit?
Can't you think of a solution?

cc https://github.com/jekyll/github-metadata/issues/116

Regards,
Max

**Comment by BaseMax** [comment]
Anyway, I raised this. To clarify this problem.
Whether it is from the **jekyll** project or the GitHub.


It may be necessary **GitHub** create a integration gateway to automatically send a request after changing the domain address (or enforcing HTTPS) to re-execute the script and update deployed files.

**Comment by ashmaroli** [comment]
> But why do we really need to send/push a useless commit?

Simply put, a Jekyll site is built *on-demand*.

The trigger on GitHub is webhook which is designed to be triggered by a commit push.
Technically, there is no need to push an empty commit if you have admin-level access to rerun the webhook. Just hitting the `rerun webhook` button would do the needful.
But that isn't for novice users to toy around with.. and advanced users would know how to peruse information, get to that button and use it.. :wink:
