### ISSUE TITLE
Potential error when github-metadata and jekyll-redirect-from are used on the same site

### ISSUE THREAD

**Issue by WasabiFan** [jekyll/github-metadata#22]
When a site includes both `github-metadata` and `jekyll-redirect-from` on the same site, it seems that the two gems can interfere and cause build errors.

The error occurs when a site includes the GH metadata gem and builds any page that contains a `redirect_from` attribute in the frontmatter. The full error text and trace are linked to below; long story short, the redirect gem is getting something of type `Jekyll::GitHubMetadata::Value` and attempting to `join()` it with a string.

I can repro this on both Windows and Ubuntu (clean install) using my test repo [here](https://github.com/WasabiFan/curly-parakeet). I also have a full terminal session log from initial boot of a new Ubuntu VM to the site build throwing errors that you can see [here](https://gist.github.com/WasabiFan/5ab8fcfd51299782884f). The latter link includes the full error trace.

It seems that this is somewhat environment-dependent, as I can repro it on some machines but not others. But given that this happens on a completely empty VM, I can be pretty sure that the problem is not isolated to something specific to my PCs.

**Comment by parkr** [comment]
I believe you are right! Jekyll-redirect-from was built for straight up string values and should do a bit of conversion to ensure the types are as it wishes them to be. One of the joys of dynamically-types languages, I suppose!

Want to contribute a PR to Jekyll-redirect-from? Wherever it reads from site.github has to call #to_s or some equivalent to ensure it is always a string.

**Comment by WasabiFan** [comment]
> Want to contribute a PR to Jekyll-redirect-from? Wherever it reads from site.github has to call #to_s or some equivalent to ensure it is always a string.

I admit I don't have any experience with Ruby, but I'm happy to give it a shot! I'll check it out and see what I can do.

**Comment by WasabiFan** [comment]
Should I close this issue and open one on the redirect-from repo? I had a 50-50 shot with picking a repo, and it looks like I guessed wrong :wink:

**Comment by parkr** [comment]
Yes please, but please reference this issue. Or just a PR :-)

**Comment by WasabiFan** [comment]
OK, I'll close this now and reference this issue in my PR.
