### ISSUE TITLE
GitHub Metadata : build_revision is always NIL

### ISSUE THREAD

**Issue by BenSouchet** [jekyll/github-metadata#220]
### Description
I have currently an issue with themes for github pages where the variable `site.github.build_revision` is always NIL.
I think this it's an issue when the github page is build (bundler maybe), the variable git_commit_sha cannot be retrieve.

#### Disclaimer
This is maybe not the best place to put my issue but you guys working on github-metadata are the most experienced to find the origin of the bug or give ideas to try to fix the bug.

### Informations
To be sure it's global I did some basic reproduction steps:
- Creating a new github repository with a README.md
- Configure a Github page in the Github repository settings
- Selected a Theme (for exemple **Cayman**)
- Waited the end of the build in the Actions tab
- Locked in the page source of the github.io page for the stylesheet link where the version need to be concatenated

The link is `<link rel="stylesheet" href="/test_101/assets/css/style.css?v=">`, there is nothing after the `v=`.

I checked every GitHub Metadata by adding these lines in the html :
```
<pre id="jekyll-debug"></pre>
<script>
  var obj = JSON.parse(decodeURIComponent("{{ site.github | jsonify | uri_escape }}"));
  var prettyJson = JSON.stringify(obj, null, 4);  // Pretty-printed JSON (indented 4 spaces).
  document.getElementById("jekyll-debug").textContent = prettyJson;
</script>
```
and the **site.github.build_revision** (a.k.a git_commit_sha if i'm not wrong) is the only empty value.

### More details
- At the end of the "Build page with Jekyll" part of the build process we can found that:
```GitHub Metadata: Generating for BenSouchet/test_101
   GitHub Metadata: Calling @client.repository("BenSouchet/test_101", {:accept=>"application/vnd.github.drax-preview+json"})
   GitHub Metadata: Calling @client.pages("BenSouchet/test_101", {})
fatal: not a git repository (or any of the parent directories): .git
           Writing: /github/workspace/docs/_site/assets/css/style.css
           Writing: /github/workspace/docs/_site/index.html
                    done in 0.624 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```
**So there is an ISSUE** , maybe related to [this](https://github.com/rubygems/bundler/issues/6453).
- I tried to add lot of settings in the `_config.yml` my file ended up a bit like that:
```
theme: jekyll-theme-cayman
title: Test 101
description: Bug testing
repository: BenSouchet/test_101
encoding: UTF-8
plugins:
- jekyll-remote-theme
- jekyll-github-metadata
```
And this still didn't work.

**Comment by benbalter** [comment]
Fix in progress via https://github.com/actions/jekyll-build-pages/pull/7.

**Comment by yoannchaudet** [comment]
And this is fixed now. Sorry for the inconvenience and thank you for catching this one!
