### ISSUE TITLE
any plan to implement site.github.public_repositories[].contributors ?

### ISSUE THREAD

**Issue by 9bow** [jekyll/github-metadata#233]
Hello,

I'm running a GitHub organization, and I would like to publish contributor list of all public repos in organization to our website.

In this regard, I was expecting the following code, but the field `site.github.public_repositories[].contributors` was not exist.

```
{% for repository in site.github.public_repositories %}
  ## [{{ repository.name }}]({{ repository.html_url }})
  {% for contributor in repository.contributors %}
    * [{{ contributor.name }}]({{ contributor.html_url }})
  {% endfor %}
{% endfor %}
```

I found [an old similar issue](https://github.com/jekyll/github-metadata/issues/26) with this feature, but it seems to have been resolved by fetching only the contributors of only one repository (the current repository specified in `_config.yaml`) as `site.github.contributors`.

It looks like the [GitHub API](https://docs.github.com/en/rest/repos/repos#list-repository-contributors) and [octokit.rb](https://github.com/octokit/octokit.rb/blob/d1628ebd3e71aeb1534b3115c8bf37e8fb42068f/lib/octokit/client/repositories.rb#L469) support the feature to get a list of contributors by repository.

However, I'm a bit embarrassed because I haven't written code in ruby. :sweat_smile:

Do you have any plans to add a feature related to this?

Thank you.

**Comment by 9bow** [comment]
New feature added as PR (#234) to close this issue.
This feature has been merged with the dedicated help of maintainer @parkr.
With his review, this PR was a great experience for me. :)

**Comment by parkr** [comment]
Thank you for the contribution, @9bow!
