### ISSUE TITLE
Is it possible to get one's  sum of total star?

### ISSUE THREAD

**Issue by guofei9987** [jekyll/github-metadata#246]
Is it possible to get one's  sum of total star?

**Comment by parkr** [comment]
Hi! This is best asked on our discussion forum Jekyll Talk: https://talk.jekyllrb.com

I'm assuming you mean the total number of stars that all the repositories on a given account have. So if I have two repositories, one with 10 stars and another with 15 stars, then the goal is to sum these into 25 stars.

A sum is [not returned from `/user`](https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28), so the only way is to iterate through all the repositories for the account and [sum `stargazers_count`](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository).
