### ISSUE TITLE
Getting new repos requires a change in the html/jekyll

### ISSUE THREAD

**Issue by Haroenv** [jekyll/github-metadata#25]
This isn't optimal, and causes new content to not appear for long times.

**Comment by parkr** [comment]
@Haroenv Can you describe what you mean by "a change in the html/jekyll"? 

You will need to rebuild your site to get a new list of repos, but this is just how jekyll works.

**Comment by mischah** [comment]
The question is how to trigger a rebuild with github hosted jekyll pages.

In that case the only way to trigger a rebuild seems to change something and push to `gh-pages` branch.

**Comment by Haroenv** [comment]
Yep, I just realised that this is more a github pages issue than a jekyll issue.

**Comment by parkr** [comment]
Easiest way is to push an empty commit for now. GitHub will have to offer something themselves, unfortunately.

**Comment by Haroenv** [comment]
Okay, that's pretty clear. Wrong place for this then.

**Comment by parkr** [comment]
No problem! I think GitHub will be sympathetic to your cause :smile:
