### ISSUE TITLE
Add support for dotenv, if present

### ISSUE THREAD

**Issue by benbalter** [jekyll/github-metadata#51]
To allow folks to keep tokens and environmental variables in a site-specific `.env` file.

**Comment by parkr** [comment]
💗

**Comment by rriemann** [comment]
is this functionally documented?

I suggest adding one phrase to the readme.

Personally, I do not understand in which case a jekyll project can now access the variables in `.env`.

**Comment by DirtyF** [comment]
@rriemann see https://github.com/jekyll/github-metadata/pull/92
