### ISSUE TITLE
Don't warn that no token is present, if no `site.github` calls are made

### ISSUE THREAD

**Issue by benbalter** [jekyll/github-metadata#52]
In other words, don't init the client until it's first called.

That way, the default use case (via the Pages Gem), will not throw a warning if the user is not using `site.github` at all (and thus doesn't need a token).

**Comment by parkr** [comment]
@benbalter This is automatically added by the generator because Jekyll always runs `GHPGenerator#generate` during the site build. Are you suggesting we throw a warning instead if no token exists? I believe we only call the API if it's asked for but I guess we could also add another layer which only initializes the client once an API call is attempted?

**Comment by benbalter** [comment]
> This is automatically added by the generator because Jekyll always runs `GHPGenerator#generate` during the site build. Are you suggesting we throw a warning instead if no token exists?

Think about this from the user's perspective:

* I don't make any `site.github` calls.
* I add `group: :jekyll_plugins` to `gem 'github-pages'`
* `jekyll-github-metadata` is now activated by default
* I build my site as I do normally
* I get a line of scary yellow text telling me I need a personal access token, but have no idea what that is or why. I just want to build my site.

Instead, it should be:

1. I don't use `site.github` at all and since the client is lazy loaded, it's never loaded, so I'm none the wiser
2. I use `site.github`, and when I make my first call, it'll look for the token, and throw a warning if none is present

**Comment by parkr** [comment]
Makes perfect sense from a UX perspective. Sounds like we should just be calling `#nwo` and actually building the client, etc. only when the user calls out to `site.github`. I do that in [jekyll-last-modified-at by using a `Determinator` class whose `#to_liquid` method does the "dirty work"](https://github.com/gjtorikian/jekyll-last-modified-at/blob/master/lib/jekyll-last-modified-at/determinator.rb#L49-L51). We could do something similar here.
