### ISSUE TITLE
Fail gracefully without network access

### ISSUE THREAD

**Issue by jpouellet** [jekyll/github-metadata#82]
Currently, trying to `bundle exec jekyll serve` a page not even using jekyll-github-metadata fails, because the jekyll-github-metadata plugin is (unconditionally, afaict) pulled in as a dependency of github-pages.

The failure mode is like this:
```
% bundle exec jekyll serve       
Configuration file: /home/user/qubesos.github.io/_config.yml
Configuration file: /home/user/qubesos.github.io/_config.yml
            Source: /home/user/qubesos.github.io
       Destination: /home/user/qubesos.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 9.53 seconds.
 Auto-regeneration: enabled for '/home/user/qubesos.github.io'
Configuration file: /home/user/qubesos.github.io/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2016-12-11 08:05:11    GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: Failed to open TCP connection to api.github.com:443 (No route to host - connect(2) for "api.github.com" port 443)
   GitHub Metadata: Failed to open TCP connection to api.github.com:443 (No route to host - connect(2) for "api.github.com" port 443)
   GitHub Metadata: Failed to open TCP connection to api.github.com:443 (No route to host - connect(2) for "api.github.com" port 443)
   GitHub Metadata: Failed to open TCP connection to api.github.com:443 (No route to host - connect(2) for "api.github.com" port 443)
   GitHub Metadata: Failed to open TCP connection to api.github.com:443 (No route to host - connect(2) for "api.github.com" port 443)
   GitHub Metadata: Failed to open TCP connection to api.github.com:443 (No route to host - connect(2) for "api.github.com" port 443)
```

See also: https://github.com/github/pages-gem/issues/364

**Comment by jpouellet** [comment]
I guess the issue here is it would be good to not try to connect to github unless `site.github.*` is actually used.

**Comment by jpouellet** [comment]
Although given the way templating works, I don't know if that's even possible, so providing an alternative to somehow disable the online lookup would be an acceptable resolution IMO.

**Comment by S0AndS0** [comment]
I've found two possible solutions, however, both options have pros and cons; option one allows for setting an alternate link or notification but is a bit more code to juggle, option two shouldn't require any modifications to current themes and what not but will cause broken links or non-rendered elements to be missing if ya ever push locally built pages to a host.


# Option one


Set the Jekyll environment variable manually to something like `airgapped` within a `_config_headless.yml` loaded with the following command


    bundle exec jekyll serve --config _config.yml,_config_headless.yml


... or set the environment veritable at run time...


    JEKYLL_ENV=airgapped bundle exec jekyll serve --config _config.yml,_config_headless.yml


... and wrap any GitHub API related calls in your template with the following...


    {% unless jekyll.environment == 'airgapped' %}
        {% comment %}Put GitHub API calls here{% endcomment %}
         <a href="{{ site.github.zip_url }}" class="btn">Download as .zip</a>
    {% else %}
        <h4>Cannot access GitHub API</h4> Jekyll environment: {{ jekyll.environment }}
    {% endunless %}


... or to avoid info leakage of local environment variables...


    {% if jekyll.environment == 'production' %}
        <a href="{{ site.github.tar_url }}" class="btn">Download as .tar.gz</a>
    {% else %}
        <h4>Cannot access GitHub API</h4> Jekyll environment: {{ jekyll.environment }}
    {% endif %}


Note the above two Liquid code examples pretty much do the same thing, just expressed differently, so choose one to test with locally. And for comparison with your local build environment variables check the ones that one of my projects' pages exposes among other info within the [about.html - rendered](https://s0ands0.github.io/Perinoid_Pipes/_pages/about.html) & [about.html - source](https://github.com/S0AndS0/Perinoid_Pipes/blob/gh-pages/_pages/about.html) for what GitHub sets environment variables to.


# option two


Set the following configuration lines in a `_net_down_config.yml` file and serve similarly to what option one showed


    liquid:
      error_mode: warn


Loading the configuration file example again


    bundle exec jekyll serve --config _config.yml,_net_down_config.yml


It'll pop errors but should serve locally, though possibly a little broken.
