### ISSUE TITLE
Option to disable GitHub metadata when running locally

### ISSUE THREAD

**Issue by pacomendes** [jekyll/github-metadata#93]
We use Jekyll to build documentation locally using the `github-pages` gem. We often don't need Github metadata and the warnings or errors often throw our content writers.

Is it possible to provide a way of disabling Github metadata so that the warnings don't appear on local builds?

**Comment by benbalter** [comment]
> We often don't need Github metadata and the warnings or errors often throw our content writers.

Can you past some of those warnings and errors? We've been working to hide them and fail silently whenever possible.

**Comment by pacomendes** [comment]
Our documentation is on github enterprise and github organization repositories.

We're running locally using bundler with:

Gemfile:
```
source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
```

Gemfile.lock
```
    ...
    github-pages (122)
      jekyll-github-metadata (= 2.3.1)
   ...
```

_config.yml (to disable error):
`repository: {blank}` or `repository: `username/repo-name`

Jekyll Serve Incremental:
`bundle exec jekyll serve --incremental`

Observed Output with warning:
```
  Server address: http://127.0.0.1:4000/docs/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2017-02-16 12:23:24    GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
...done in 19.653869 seconds.
      Regenerating: 1 file(s) changed at 2017-02-16 12:23:44 ...done in 5.33376 seconds.
      Regenerating: 1 file(s) changed at 2017-02-16 12:23:49 ...done in 5.229096 seconds.
      Regenerating: 1 file(s) changed at 2017-02-16 12:23:55 ...done in 6.140592 seconds.
```

The initial regeneration takes long due to the API lookup. Subsequent generations do not have warnings.

We're not using any github metadata for our pages, so would ideally like to disable this lookup to speed up that initial regeneration.

**Comment by pacomendes** [comment]
@benbalter. The delay in regeneration is proving to be an issue for our writers seeing their initial changes locally... Are there any other workarounds that you know of to disable this check/plugin?

**Comment by pacomendes** [comment]
Our work around is just to just the jekyll gem and no longer use github-pages in our Gemfile

`source 'https://rubygems.org'
gem 'jekyll', '3.3.1'`

https://github.com/mmistakes/minimal-mistakes/issues/570

**Comment by pacomendes** [comment]
Thanks @benbalter and @parkr. Generation times are ok on a `jekyll build` and an initial `jekyll serve`. The lag is experienced after the first edit on a running server:

>    `bundle exec jekyll serve --verbose --profile `
>    ...
>    Generating: JekyllOptionalFrontMatter::Generator finished in 0.000321 seconds.
>    GitHub Metadata: Initializing...
>    GitHub Metadata: Generating for org-abc/repo-abc
>    **GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
>    GitHub Metadata: Calling @client.pages("org-abc/repo-abc", {})
>    GitHub Metadata: Generating for org-abc/repo-abc
>    GitHub Metadata: Calling @client.pages("org-abc/repo-abc", {})
>    GitHub Metadata: Calling @client.contributors("org-abc/repo-abc")
>    GitHub Metadata: Calling @client.contributors("org-abc/repo-abc")
>    GitHub Metadata: Calling @client.repository("org-abc/repo-abc")
>    GitHub Metadata: Calling @client.repository("org-abc/repo-abc")
>    GitHub Metadata: Calling @client.organization("org-abc")
>    GitHub Metadata: Calling @client.organization("org-abc")
>    GitHub Metadata: Calling @client.list_repos("org-abc", {"type"=>"public"})
>    GitHub Metadata: Calling @client.list_repos("org-abc", {"type"=>"public"})
>    GitHub Metadata: Calling @client.releases("org-abc/repo-abc")
>    GitHub Metadata: Calling @client.releases("org-abc/repo-abc")
>          Generating: Jekyll::GitHubMetadata::GHPMetadataGenerator finished in 15.787973 seconds.**
>         Generating: JekyllReadmeIndex::Generator finished in 0.000109 seconds.
>         Generating: JekyllRelativeLinks::Generator finished in 2.7e-05 seconds.
>         Generating: JekyllTitlesFromHeadings::Generator finished in 1.4e-05 seconds.
>         Generating: JekyllDefaultLayout::Generator finished in 2.5e-05 seconds.
>         Generating: Jekyll::Paginate::Pagination finished in 8.0e-06 seconds.

(I've replaced repo and org names in this log)

**Comment by parkr** [comment]
@pacomendes If you're able to, would you mind testing the above PR, #95?
